"""This module contains the level data.

Level data will be automatically generated by the Tiled software.
"""


level_data = {
    "test_level": {
        "music": "game_assets/music/test_level/inspiring-cinematic-ambient-116199.ogg",
        "ground": "game_assets/level_layout/test_level/test_map_terrain.csv",
        "rocks": "game_assets/level_layout/test_level/test_map_rocks.csv",
        "raised_ground": "game_assets/level_layout/test_level/test_map_high_ground.csv",
        "plants": "game_assets/level_layout/test_level/test_map_plants.csv",
        "fence": "game_assets/level_layout/test_level/test_map_fence.csv",
        "extra": "game_assets/level_layout/test_level/test_map_extra.csv",
        "characters": "game_assets/level_layout/test_level/test_map_characters.csv",
        "items": "game_assets/level_layout/test_level/test_map_items.csv",
    },
}

menu_data = {
    "main_menu": {
        "music": "game_assets/music/main_menu/science-documentary-169621.mp3",
        "background_image_path": "game_assets/graphics/main_menu/ground.png",
    }
}

character_keys = {
    "player": "1242",
    "damsel": "1243",
    "skeleton": "1241",
    "minotaur": "1178",
    "postman": "1180",
}

item_keys = {"crystal": "1301"}
