"""This module contains the level data.

Level data will be automatically generated by the Tiled software.
"""

tileset_path = "test/test_assets/tileset.png"
asset_path = "test/test_assets"
level_path = asset_path + "/level_layout"
level_config_name = "general_setup"

level_data = {
    "test_level": {
        "music": level_path + "/test_level/inspiring-cinematic-ambient-116199.ogg",
        "ground": level_path + "/test_level/" + level_config_name + "_terrain.csv",
        "rocks": level_path + "/test_level/" + level_config_name + "_rocks.csv",
        "raised_ground": level_path
        + "/test_level/"
        + level_config_name
        + "_high_ground.csv",
        "plants": level_path + "/test_level/" + level_config_name + "_plants.csv",
        "fence": level_path + "/test_level/" + level_config_name + "_fence.csv",
        "extra": level_path + "/test_level/" + level_config_name + "_extra.csv",
        "characters": level_path
        + "/test_level/"
        + level_config_name
        + "_characters.csv",
        "items": level_path + "/test_level/" + level_config_name + "_items.csv",
    },
}

menu_data = {
    "main_menu": {
        "music": "test/test_assets/music/main_menu/science-documentary-169621.mp3",
        "background_image_path": "test_assets/graphics/main_menu/ground.png",
    }
}

character_keys = {
    "player": "87",
    "damsel": "88",
    "skeleton": "86",
    "minotaur": "66",
    "postman": "68",
}

item_keys = {"crystal": "1301"}
