"""This module contains the level data.

Level data will be automatically generated by the Tiled software.
"""

tileset_path = "test_assets/test_map/general_setup.tmx"

level_data = {
    "test_level": {
        "music": "test_assets/music/test_level/inspiring-cinematic-ambient-116199.ogg",
        "ground": "test_assets/level_layout/test_level/test_map_terrain.csv",
        "rocks": "test_assets/level_layout/test_level/test_map_rocks.csv",
        "raised_ground": "test_assets/level_layout/test_level/test_map_high_ground.csv",
        "plants": "test_assets/level_layout/test_level/test_map_plants.csv",
        "fence": "test_assets/level_layout/test_level/test_map_fence.csv",
        "extra": "test_assets/level_layout/test_level/test_map_extra.csv",
        "characters": "test_assets/level_layout/test_level/test_map_characters.csv",
        "items": "test_assets/level_layout/test_level/test_map_items.csv",
    },
}

menu_data = {
    "main_menu": {
        "music": "test_assets/music/main_menu/science-documentary-169621.mp3",
        "background_image_path": "test_assets/graphics/main_menu/ground.png",
    }
}

character_keys = {
    "player": "87",
    "damsel": "88",
    "skeleton": "86",
    "minotaur": "66",
    "postman": "68",
}

item_keys = {"crystal": "1301"}
