"""This module contains the level data.

Level data will be automatically generated by the Tiled software.
"""
level_1 = {
    "ground": "levels/testing_level/testing-map_terrain.csv",
    "rocks": "levels/testing_level/testing-map_rocks.csv",
    "raised_ground": "levels/testing_level/testing-map_raised-ground.csv",
    "plants": "levels/testing_level/testing-map_plants.csv",
    "fence": "levels/testing_level/testing-map_fence.csv",
    "extra": "levels/testing_level/testing-map_extra.csv",
    "characters": "levels/testing_level/testing-map_charaters.csv",
}
character_keys = {
    "player": "1242",
    "damsel": "1243",
    "skeleton": "1241",
}
