name: Lint Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install python3-pygame
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --max-complexity=15 --max-line-length=88 --statistics
    - name: Lint with black
      run: |
        pip install black
        black . --check
    - name: Lint with pydocstyle
      run: |
        pip install pydocstyle
        pydocstyle .